version: '3.8'

services:
  app:
    image: webdevops/php-apache:8.4
    container_name: cakephp_app
    environment:
      - WEB_DOCUMENT_ROOT=/app/webroot
    ports:
      - "8765:80"
    volumes:
      - .:/app:Z
